/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Display;

import Clases.Carrito;
import Clases.Conexion;
import Clases.Productos;
import Data.DataProductos;
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.net.URL;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTable;


/**
 *
 * @author Usuario
 */
public class JCarrito extends javax.swing.JFrame {

    /**
     * Creates new form JCarrito
     */
    public JCarrito() {
        initComponents();
        llenarProductos();
        cargarTablaCarrito();
        ButtonGroup btnAnnadir;
        btnAnnadir = new ButtonGroup();

    }

    private ArrayList<Productos> listaProductos;

    private void llenarProductos() {

        DataProductos dtProductos = new DataProductos();
        listaProductos = dtProductos.getProductos();  // Inicializar la listaProductos

        cboProductos.removeAllItems();

        for (int i = 0; i < listaProductos.size(); i++) {
            cboProductos.addItem(listaProductos.get(i).getDescripcion());
        }

        cboProductos.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {

                if (e.getStateChange() == ItemEvent.SELECTED) {
                    int selectedProductIndex = cboProductos.getSelectedIndex();
                    if (selectedProductIndex != -1) {
                        int cantidad = (int) listaProductos.get(selectedProductIndex).getInventario();
                        lblDisponible.setText(cantidad + "");
                    }
                }

            }
        });
    }

    public void limpiar() {
        cboProductos.getSelectedIndex();
        lblDisponible.getText();
        TxtPrecio.setText("");
        TxtIva.setText("");
        Txt_IncEnvio.setText("");
        TxtTotal.setText("");
        //  btnAgregar.clearSelection();

    }

    private void cargarTablaCarrito() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tblCarrito.getModel();
        modeloTabla.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int column;
        int[] width = {10, 40, 50, 60, 80, 90};
        for (int i = 0; i < tblCarrito.getColumnCount(); i++) {
            tblCarrito.getColumnModel().getColumn(i).setPreferredWidth(width[i]);
        }
        try {
            Connection connection = Conexion.getConexion();
            ps = connection.prepareStatement("SELECT Descripcion,Cantidad,Precio,Iva, Envio, Total FROM Carrito");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            column = rsmd.getColumnCount();
            while (rs.next()) {
                Object[] row = new Object[column];
                for (int index = 0; index < column; index++) {
                    row[index] = rs.getObject(index + 1);

                }
                modeloTabla.addRow(row);

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jL_CarritoTitulo = new javax.swing.JLabel();
        txtValorPrecio = new javax.swing.JTextField();
        TxtValorIva = new javax.swing.JTextField();
        cboProductos = new javax.swing.JComboBox<>();
        TxtValorTotal = new javax.swing.JTextField();
        jS_Cantidad = new javax.swing.JSpinner();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarrito = new javax.swing.JTable();
        lblDisponible = new javax.swing.JLabel();
        TxtPrecio = new javax.swing.JTextField();
        TxtIva = new javax.swing.JTextField();
        Txt_IncEnvio = new javax.swing.JTextField();
        TxtTotal = new javax.swing.JTextField();
        btnPagar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        rbSi = new javax.swing.JRadioButton();
        rbNo = new javax.swing.JRadioButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Compras");
        setBackground(new java.awt.Color(102, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102))));

        jL_CarritoTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jL_CarritoTitulo.setText("Carrito de compras");

        txtValorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorPrecioActionPerformed(evt);
            }
        });

        TxtValorIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtValorIvaActionPerformed(evt);
            }
        });

        cboProductos.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));
        cboProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboProductosActionPerformed(evt);
            }
        });

        TxtValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtValorTotalActionPerformed(evt);
            }
        });

        jS_Cantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jS_Cantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jS_Cantidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad"));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        tblCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCarrito.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblCarritoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tblCarrito);

        lblDisponible.setBackground(new java.awt.Color(255, 255, 255));
        lblDisponible.setForeground(new java.awt.Color(255, 255, 255));
        lblDisponible.setBorder(javax.swing.BorderFactory.createTitledBorder("Disponible"));

        TxtPrecio.setText("Precio");

        TxtIva.setText("Iva");

        Txt_IncEnvio.setText("Incluir Envio");

        TxtTotal.setText("Total");

        btnPagar.setText("Pagar");

        btnImprimir.setText("Imprimir Factura");

        rbSi.setText("Si");

        rbNo.setText("No");
        rbNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TxtPrecio)
                                    .addComponent(TxtIva)
                                    .addComponent(Txt_IncEnvio)
                                    .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtValorIva, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtValorPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(91, 91, 91)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbSi)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbNo))))
                            .addComponent(jL_CarritoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jS_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 78, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jL_CarritoTitulo)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                        .addComponent(jS_Cantidad))
                    .addComponent(lblDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtValorIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_IncEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbSi)
                    .addComponent(rbNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(189, 189, 189))
        );

        lblDisponible.getAccessibleContext().setAccessibleParent(lblDisponible);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboProductosActionPerformed

    private void TxtValorIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtValorIvaActionPerformed
//DEBO AGREGAR EL VALOR DEL IVA
       masIva(); 
    }
    private void masIva() {
    DefaultTableModel model = (DefaultTableModel) tblCarrito.getModel();

    double sumatotalIva = 0;
    for (int row = 0; row < model.getRowCount(); row++) {
        int cantidad = (int) model.getValueAt(row, 1); // Obtener la cantidad
        double precio = (double) model.getValueAt(row, 2); // Obtener el precio
        double subtotalIva =  (precio *0.20); // Calcular el subtotal
        sumatotalIva += subtotalIva; // Acumular al total
    }

        TxtValorIva.setText(String.valueOf(sumatotalIva));
          
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtValorIvaActionPerformed

    private void TxtValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtValorTotalActionPerformed
        int valorTotal=0;
     
    }
    private void valorTotal() {
    DefaultTableModel model = (DefaultTableModel) tblCarrito.getModel();

    double sumatotalIva =0;
    for (int row = 0; row < model.getRowCount(); row++) {
        int cantidad = (int) model.getValueAt(row, 1); // Obtener la cantidad
        double precio = (double) model.getValueAt(row, 2); // Obtener el precio
        double valorTotal = precio + (precio * (0.20)) ; // Calcular el subtotal
        sumatotalIva += valorTotal; // Acumular al total
        
                TxtValorTotal.setText(String.valueOf(sumatotalIva));
    }
            // TODO add your handling code here:
    }//GEN-LAST:event_TxtValorTotalActionPerformed


    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        ImageIcon icono = new ImageIcon("src\\main\\java\\Imagenes\\anadir-al-carrito.png");
        btnAgregar.setIcon(icono);

  
        String comboBoxValue = cboProductos.getSelectedItem().toString();
        int selectedProductIndex = cboProductos.getSelectedIndex();
        int cantidad = (int) this.jS_Cantidad.getValue();

        if (selectedProductIndex != -1 && cantidad > 0) {
            Productos selectedProduct = listaProductos.get(selectedProductIndex); // Obtener el producto seleccionado
            double precio = selectedProduct.getPrecio();

            double subtotal = precio * cantidad;

            DefaultTableModel model = (DefaultTableModel) tblCarrito.getModel();
            model.addRow(new Object[]{cboProductos.getSelectedItem(), this.jS_Cantidad.getValue(), subtotal});
       
      
            calcularTotal(); // Llamar al método para recalcular el total      
                 masIva(); 
                 valorTotal();
        }
        
    
  //      selectedProductIndex = 0;
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        JLogin jLogin = new JLogin();
        jLogin.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void txtValorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorPrecioActionPerformed
    calcularTotal(); 
    }
    private void calcularTotal() {
    DefaultTableModel model = (DefaultTableModel) tblCarrito.getModel();

    double sumatotal = 0;
    for (int row = 0; row < model.getRowCount(); row++) {
        int cantidad = (int) model.getValueAt(row, 1); // Obtener la cantidad
        double precio = (double) model.getValueAt(row, 2); // Obtener el precio
        double subtotal =  precio; // Calcular el subtotal
        sumatotal += subtotal; // Acumular al total
    }

    
    if (rbSi.isSelected()) {  // Si el RadioButton de incluir envío está seleccionado
        sumatotal += calcularCostoEnvio(sumatotal);
    }
    txtValorPrecio.setText(String.valueOf(sumatotal));
    
       
    }//GEN-LAST:event_txtValorPrecioActionPerformed

    
    private double calcularCostoEnvio(double total) {

    return total * 0.3;  //  30% del total
    
    }
    private void tblCarritoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblCarritoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCarritoAncestorAdded

    private void rbNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoActionPerformed




    
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCarrito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtIva;
    private javax.swing.JTextField TxtPrecio;
    private javax.swing.JTextField TxtTotal;
    private javax.swing.JTextField TxtValorIva;
    private javax.swing.JTextField TxtValorTotal;
    private javax.swing.JTextField Txt_IncEnvio;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox<String> cboProductos;
    private javax.swing.JLabel jL_CarritoTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSpinner jS_Cantidad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDisponible;
    private javax.swing.JRadioButton rbNo;
    private javax.swing.JRadioButton rbSi;
    private javax.swing.JTable tblCarrito;
    private javax.swing.JTextField txtValorPrecio;
    // End of variables declaration//GEN-END:variables

    private ActionEvent setText(String valueOf) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
