
package Display;

import Clases.Productos;
import Data.DataProductos;
import Clases.Usuarios;
import java.awt.Image;
import java.awt.List;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.TableModel;

/**
 *
 * @author Usuario
 */
public class JFrameCarrito extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCarrito
     */
    public JFrameCarrito() {

        initComponents();
        llenarProductos();

        ImageIcon icono = new ImageIcon("src\\main\\java\\Imagenes\\carrito.png");
//        jButton_Agregar.setIcon(icono);
        calcularPrecio();

    }
    
      private void llenarProductos(){
     
          DataProductos dtProductos = new DataProductos();
          ArrayList<Productos> listaProductos = dtProductos.getProductos();
          jComboBox_Producto.removeAllItems();
          
          for (int i = 0; i < listaProductos.size(); i++) {
    jComboBox_Producto.addItem(listaProductos.get(i).getDescripcion());
    
            
            }
      }
    
//      public void calcularPrecio(){
//        DataProductos dtProductos = new DataProductos();
//          ArrayList<Productos> listaPoductos = dtProductos.getprecio();
//          jButton_Precio();
//          
//          for (int i = 0; i < listaProductos.size(); i++) {
//    jComboBox_Producto.addItem(listaProductos.get(i).getPR());
//            
//            }
//      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTextField_Precio = new javax.swing.JTextField();
        jButton_Precio = new javax.swing.JButton();
        jComboBox_Producto = new javax.swing.JComboBox<>();
        jSpinner_Cantidad = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ProductosComprar = new javax.swing.JTable();
        jTextField_IVA = new javax.swing.JTextField();
        jLabel_CarritodeCompras = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton_TotalPagar = new javax.swing.JButton();
        jTextField_Total = new javax.swing.JTextField();
        jTextField_IncluirEnvio = new javax.swing.JTextField();
        jComboBox_Envio = new javax.swing.JComboBox<>();
        jButton_IVA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField_Precio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_Precio.setText("Precio");
        jTextField_Precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PrecioActionPerformed(evt);
            }
        });

        jButton_Precio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Precio.setText("$0.00");
        jButton_Precio.setPreferredSize(new java.awt.Dimension(10, 10));
        jButton_Precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PrecioActionPerformed(evt);
            }
        });

        jComboBox_Producto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox_Producto.setMaximumRowCount(100);
        jComboBox_Producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Producto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jComboBox_Producto.setMinimumSize(new java.awt.Dimension(0, 100));
        jComboBox_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ProductoActionPerformed(evt);
            }
        });

        jSpinner_Cantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSpinner_Cantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jSpinner_Cantidad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jSpinner_Cantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_CantidadStateChanged(evt);
            }
        });

        jTable_ProductosComprar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_ProductosComprar.setMaximumSize(new java.awt.Dimension(10, 10));
        jScrollPane1.setViewportView(jTable_ProductosComprar);

        jTextField_IVA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_IVA.setText("IVA");
        jTextField_IVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IVAActionPerformed(evt);
            }
        });

        jLabel_CarritodeCompras.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_CarritodeCompras.setText("Carrito de compras");

        jButton_TotalPagar.setLabel("");
        jButton_TotalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TotalPagarActionPerformed(evt);
            }
        });

        jTextField_Total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_Total.setText("Total");

        jTextField_IncluirEnvio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_IncluirEnvio.setText("Incluir Envio");
        jTextField_IncluirEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IncluirEnvioActionPerformed(evt);
            }
        });

        jComboBox_Envio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Envio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_EnvioActionPerformed(evt);
            }
        });

        jButton_IVA.setText("jButton1");
        jButton_IVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IVAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField_IVA, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(jTextField_Precio))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_IVA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_IncluirEnvio)
                                    .addComponent(jTextField_Total))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_TotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox_Envio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_CarritodeCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(jSpinner_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_CarritodeCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_IVA, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_IVA))
                        .addGap(16, 16, 16)
                        .addComponent(jTextField_IncluirEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jComboBox_Envio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_Total, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jButton_TotalPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(196, 196, 196))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_PrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PrecioActionPerformed

    private void jButton_PrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PrecioActionPerformed
       calcularPrecio();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_PrecioActionPerformed

    private void jComboBox_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ProductoActionPerformed
            calcularPrecio();
     
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ProductoActionPerformed

    private void jSpinner_CantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner_CantidadStateChanged
       calcularPrecio();
// TODO add your handling code here:
    }//GEN-LAST:event_jSpinner_CantidadStateChanged

    private void jTextField_IVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IVAActionPerformed

    private void jButton_TotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TotalPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_TotalPagarActionPerformed

    private void jTextField_IncluirEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IncluirEnvioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IncluirEnvioActionPerformed

    private void jButton_IVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_IVAActionPerformed

    private void jComboBox_EnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_EnvioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_EnvioActionPerformed

    public void calcularPrecio() {
//        productos new productoCarrito = productos;
//        precio=precio[Productos.get.SelectedIndex()];
//        get.Productos.cantidad = Integer.parseInt(jSpinner_Cantidad.getValue().toString());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCarrito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton_IVA;
    private javax.swing.JButton jButton_Precio;
    private javax.swing.JButton jButton_TotalPagar;
    private javax.swing.JComboBox<String> jComboBox_Envio;
    private javax.swing.JComboBox<String> jComboBox_Producto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_CarritodeCompras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_Cantidad;
    private javax.swing.JTable jTable_ProductosComprar;
    private javax.swing.JTextField jTextField_IVA;
    private javax.swing.JTextField jTextField_IncluirEnvio;
    private javax.swing.JTextField jTextField_Precio;
    private javax.swing.JTextField jTextField_Total;
    // End of variables declaration//GEN-END:variables
}
